-- Migración: Prioridad 3 — captura de horas trabajadas y sistema de alertas
-- Fecha: 2026-05-17
-- Motivo: soportar P3.1 (bloques manuales de horas) y P3.2 (alertas con
-- estado leído/no leído). La tarifa $/h y los umbrales viven en `config`.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Tabla `horas_trabajadas`
--    Bloques manuales: cada uno con fecha, hora inicio, hora fin, descripción.
--    El cálculo de horas totales se hace en la app desde estas filas.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.horas_trabajadas (
  id           bigint generated by default as identity primary key,
  fecha        date not null,
  hora_inicio  time not null,
  hora_fin     time not null,
  descripcion  text,
  created_at   timestamptz not null default now()
);

comment on table public.horas_trabajadas is
  'Bloques de horas trabajadas por el operador. Permite calcular costo de oportunidad y margen neto real.';
comment on column public.horas_trabajadas.descripcion is
  'Texto libre opcional: "operación", "delivery", "compras", "diseño marketing", etc.';

-- CHECK: hora_fin debe ser mayor que hora_inicio (mismo día).
-- Si en algún momento hay turnos que cruzan medianoche, se rompen en dos bloques.
alter table public.horas_trabajadas
  drop constraint if exists horas_trabajadas_rango_check;
alter table public.horas_trabajadas
  add constraint horas_trabajadas_rango_check
  check (hora_fin > hora_inicio);

-- Índice para vistas que ordenan por fecha descendente y suman por semana/mes
create index if not exists idx_horas_trabajadas_fecha
  on public.horas_trabajadas (fecha desc);

-- RLS abierto (mismo patrón que el resto de tablas del proyecto)
alter table public.horas_trabajadas enable row level security;
drop policy if exists "horas_trabajadas_full_access" on public.horas_trabajadas;
create policy "horas_trabajadas_full_access"
  on public.horas_trabajadas
  for all
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Tabla `alertas_leidas`
--    Las alertas se generan en el frontend desde los datos (no se almacenan).
--    Esta tabla guarda cuáles ya fueron marcadas como leídas, para el badge
--    de "no leídas" y para no mostrar la misma alerta una y otra vez.
--
--    `clave` identifica la alerta de forma estable: por ejemplo
--    "cliente_frio:juan_perez:2026-05-17" o "stock_bajo:naranja:2026-05-17".
--    El que la genera arma la clave y este registro la marca como leída.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.alertas_leidas (
  clave      text primary key,
  tipo       text not null,
  leida_at   timestamptz not null default now()
);

comment on table public.alertas_leidas is
  'Registro de alertas que el usuario ya marcó como leídas. Las alertas se generan en frontend desde otros datos; aquí solo guardamos el estado.';
comment on column public.alertas_leidas.clave is
  'Identificador estable de la alerta. Ejemplos: "cliente_frio:juan_perez:2026-05-17", "stock_bajo:naranja". Incluir fecha si la alerta puede repetirse en el tiempo.';
comment on column public.alertas_leidas.tipo is
  'Categoría: cliente_frio, stock_bajo, dia_historico, sin_pautar, otro.';

create index if not exists idx_alertas_leidas_tipo
  on public.alertas_leidas (tipo);

alter table public.alertas_leidas enable row level security;
drop policy if exists "alertas_leidas_full_access" on public.alertas_leidas;
create policy "alertas_leidas_full_access"
  on public.alertas_leidas
  for all
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Claves de configuración para tarifa y umbrales de alertas
--    Misma estrategia idempotente que la migración P2: insert solo si no existe.
--    NOTA: `costo_hora_operador` y `horas_trabajadas_total` ya se insertaron
--    en la migración P2 (esos no se duplican gracias al `where not exists`).
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.config (clave, valor)
select v.clave, v.valor
from (values
  ('alerta_cliente_dias',  14),     -- días sin compra para marcar cliente VIP como frío
  ('alerta_stock_dias',    5),      -- días de stock para alerta de "stock bajo"
  ('alerta_sin_pauta_dias',5)       -- días sin pautar para alerta de marketing
) as v(clave, valor)
where not exists (
  select 1 from public.config c where c.clave = v.clave
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Rollback manual (si fuera necesario):
-- drop table if exists public.horas_trabajadas;
-- drop table if exists public.alertas_leidas;
-- delete from public.config where clave in (
--   'alerta_cliente_dias','alerta_stock_dias','alerta_sin_pauta_dias'
-- );
