-- Tabla de insights generados por IA (Parte 3 del dashboard)
-- Histórico auditable: qué dijo la IA, cuándo y con qué datos.
-- Cache: 1 análisis por día (fecha única) — recargar la vista no llama a la API.

create table if not exists insights (
  id bigint generated by default as identity primary key,
  fecha date not null unique,
  json_metricas jsonb not null,
  respuesta jsonb not null,
  modelo text,
  created_at timestamptz not null default now()
);

alter table insights enable row level security;

-- Mismo nivel de acceso que el resto de la app (sin login, rol anon)
create policy "app acceso insights" on insights
  for all to anon using (true) with check (true);
