-- Campañas de WhatsApp preparadas con IA (vista "Campañas").
-- Una campaña = un mensaje base + un texto personalizado por cliente, escrito
-- desde el PC con las fichas y las órdenes. La app solo LEE la campaña y marca
-- cada mensaje como enviado/omitido; el envío es manual (wa.me), nunca automático.
-- Escritor: `Documents/The Drink/campañas/publicar.js` (service_role, solo en el PC).

create table if not exists public.campanas (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  mensaje_base text,
  nota        text,
  estado      text not null default 'activa',   -- activa | cerrada
  creada_en   timestamptz not null default now()
);

create table if not exists public.campana_mensajes (
  id          bigint generated by default as identity primary key,
  campana_id  bigint not null references public.campanas(id) on delete cascade,
  cliente_id  uuid references public.clientes(id) on delete set null,
  nombre      text not null,
  telefono    text,
  zona        text,
  prioridad   text not null default 'media',    -- alta | media | baja
  por_que     text,                              -- por qué se le escribe (lo que dice la ficha)
  texto       text not null,                     -- el mensaje listo para WhatsApp
  estado      text not null default 'pendiente', -- pendiente | enviado | omitido
  enviado_en  timestamptz,
  creado_en   timestamptz not null default now()
);

create index if not exists campana_mensajes_campana_estado_idx
  on public.campana_mensajes (campana_id, estado);

-- Blindaje (regla del CLAUDE.md): RLS + solo authenticated.
alter table public.campanas enable row level security;
alter table public.campana_mensajes enable row level security;

drop policy if exists staff_authenticated_all on public.campanas;
create policy staff_authenticated_all on public.campanas
  for all to authenticated using (true) with check (true);

drop policy if exists staff_authenticated_all on public.campana_mensajes;
create policy staff_authenticated_all on public.campana_mensajes
  for all to authenticated using (true) with check (true);
