-- Migración: Prioridad 2 — Camino al Bar, perfil de cliente y aprendizajes
-- Fecha: 2026-05-14
-- Motivo: soportar las features críticas de P2:
--   1. tag editable por cliente (VIP, influencer potencial, probable invitado bar...)
--   2. tabla de aprendizajes (knowledge base manual del negocio)
--   3. claves de config para los objetivos del "Camino al Bar"
--      (todos editables desde la app, por eso van en la tabla config existente)

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Columna `tag` en clientes
--    Etiqueta libre que el dueño asigna manualmente para clasificar clientes.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.clientes
  add column if not exists tag text;

comment on column public.clientes.tag is
  'Etiqueta manual del cliente: VIP, Influencer potencial, Probable invitado bar, etc. Editable desde el perfil del cliente.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Tabla `aprendizajes`
--    Registro de observaciones operativas con timestamp. Knowledge base manual.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.aprendizajes (
  id          bigint generated by default as identity primary key,
  texto       text not null,
  tag         text,                       -- precio | cliente | operacion | marketing | calidad
  fecha       date not null default current_date,
  created_at  timestamptz not null default now()
);

comment on table public.aprendizajes is
  'Observaciones operativas del negocio anotadas manualmente. Knowledge base interna.';
comment on column public.aprendizajes.texto is
  'Texto libre de la observación, máximo 280 caracteres (validado en la app).';
comment on column public.aprendizajes.tag is
  'Categoría opcional: precio, cliente, operacion, marketing, calidad.';

-- CHECK suave para el tag (permite null y los 5 valores conocidos)
alter table public.aprendizajes
  drop constraint if exists aprendizajes_tag_check;
alter table public.aprendizajes
  add constraint aprendizajes_tag_check
  check (
    tag is null
    or tag = any (array['precio','cliente','operacion','marketing','calidad']::text[])
  );

-- Índices para la vista de línea de tiempo (ordena por fecha) y filtro por tag
create index if not exists idx_aprendizajes_fecha
  on public.aprendizajes (fecha desc);
create index if not exists idx_aprendizajes_tag
  on public.aprendizajes (tag)
  where tag is not null;

-- RLS: la app usa la key pública, así que se habilita acceso completo
-- (mismo patrón que el resto de tablas del proyecto, que no usan auth por fila)
alter table public.aprendizajes enable row level security;

drop policy if exists "aprendizajes_full_access" on public.aprendizajes;
create policy "aprendizajes_full_access"
  on public.aprendizajes
  for all
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Claves de configuración para el "Camino al Bar"
--    Se insertan en la tabla `config` (clave/valor) ya existente.
--    Si ya existen NO se sobrescriben, para respetar cualquier valor que el
--    dueño haya ajustado antes. Se usa "where not exists" en vez de
--    "on conflict" para no depender de que `clave` tenga un UNIQUE constraint.
--    NOTA: la columna `valor` es de tipo numeric, por eso los valores van
--    como números (sin comillas) y el margen se guarda como decimal.
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.config (clave, valor)
select v.clave, v.valor
from (values
  ('bar_objetivo_capital',  15000000),  -- capital acumulado meta (CLP)
  ('bar_objetivo_clientes', 200),       -- clientes base únicos meta
  ('bar_objetivo_recetas',  10),        -- recetas validadas meta (>=5 ventas c/u)
  ('bar_objetivo_margen',   0.65),      -- margen bruto sostenido meta (fracción)
  ('bar_horizonte_meses',   18),        -- horizonte de proyección de utilidades
  ('costo_hora_operador',   0),         -- tarifa $/hora del operador (P3.1)
  ('horas_trabajadas_total',0)          -- acumulado de horas (lo actualiza P3.1)
) as v(clave, valor)
where not exists (
  select 1 from public.config c where c.clave = v.clave
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Rollback manual (si fuera necesario):
-- alter table public.clientes drop column if exists tag;
-- drop table if exists public.aprendizajes;
-- delete from public.config where clave in (
--   'bar_objetivo_capital','bar_objetivo_clientes','bar_objetivo_recetas',
--   'bar_objetivo_margen','bar_horizonte_meses','costo_hora_operador',
--   'horas_trabajadas_total'
-- );
