-- Migración: Prioridad 3 — captura de horas trabajadas y sistema de alertas
-- Fecha: 2026-05-17
-- Motivo: soportar P3.1 (bloques manuales de horas con personas + roles),
-- P3.2 (alertas con estado leído/no leído) y P3.5 (atajos rápidos).
-- Las tarifas viven por ROL (no por persona): un mismo operador trabajando
-- en "Operación" no vale lo mismo que cuando hace "Aseo".

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Tabla `personas` — el equipo de The Drink
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.personas (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  activa      boolean not null default true,
  orden       int not null default 0,
  created_at  timestamptz not null default now()
);

comment on table public.personas is
  'Equipo que trabaja en The Drink. Cada bloque de horas pertenece a una persona.';

alter table public.personas enable row level security;
drop policy if exists "personas_full_access" on public.personas;
create policy "personas_full_access" on public.personas for all using (true) with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Tabla `roles` — qué se está haciendo (con su tarifa $/h)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.roles (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  tarifa_hora numeric not null default 0,
  color       text,                      -- color hex para el chip en la UI
  activo      boolean not null default true,
  orden       int not null default 0,
  created_at  timestamptz not null default now()
);

comment on table public.roles is
  'Tipos de trabajo en The Drink: operación, delivery, compras, marketing, aseo... Cada rol tiene su propia tarifa $/h.';
comment on column public.roles.tarifa_hora is
  'Costo de oportunidad por hora en este rol. Define el descuento en el margen neto.';

alter table public.roles enable row level security;
drop policy if exists "roles_full_access" on public.roles;
create policy "roles_full_access" on public.roles for all using (true) with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Tabla `horas_trabajadas` — bloques discontinuos por persona + rol
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.horas_trabajadas (
  id           bigint generated by default as identity primary key,
  fecha        date not null,
  hora_inicio  time not null,
  hora_fin     time not null,
  persona_id   bigint references public.personas(id) on delete set null,
  rol_id       bigint references public.roles(id) on delete set null,
  descripcion  text,
  created_at   timestamptz not null default now()
);

comment on table public.horas_trabajadas is
  'Bloques de horas trabajadas. Cada bloque pertenece a UNA persona haciendo UN rol. Las pausas (almuerzo, café) se modelan como gaps entre bloques.';
comment on column public.horas_trabajadas.descripcion is
  'Texto libre opcional: detalles del rato trabajado.';

-- Agregar columnas persona_id y rol_id si la tabla ya existía (caso de re-correr migración)
alter table public.horas_trabajadas
  add column if not exists persona_id bigint references public.personas(id) on delete set null;
alter table public.horas_trabajadas
  add column if not exists rol_id bigint references public.roles(id) on delete set null;

-- CHECK: hora_fin debe ser mayor que hora_inicio (mismo día).
alter table public.horas_trabajadas
  drop constraint if exists horas_trabajadas_rango_check;
alter table public.horas_trabajadas
  add constraint horas_trabajadas_rango_check
  check (hora_fin > hora_inicio);

create index if not exists idx_horas_trabajadas_fecha
  on public.horas_trabajadas (fecha desc);
create index if not exists idx_horas_trabajadas_persona
  on public.horas_trabajadas (persona_id);
create index if not exists idx_horas_trabajadas_rol
  on public.horas_trabajadas (rol_id);

alter table public.horas_trabajadas enable row level security;
drop policy if exists "horas_trabajadas_full_access" on public.horas_trabajadas;
create policy "horas_trabajadas_full_access"
  on public.horas_trabajadas
  for all
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Tabla `atajos_horas` — botones de 1-toque para los turnos típicos
--    Ej: "Operación tú 20:00–24:00" crea un bloque precargado con esos valores.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.atajos_horas (
  id           bigint generated by default as identity primary key,
  nombre       text not null,
  persona_id   bigint references public.personas(id) on delete cascade,
  rol_id       bigint references public.roles(id) on delete cascade,
  hora_inicio  time,
  hora_fin     time,
  descripcion  text,
  orden        int not null default 0,
  created_at   timestamptz not null default now()
);

comment on table public.atajos_horas is
  'Botones configurables de "registrar turno típico" en la página Horas. Al tocar uno se precarga el formulario con sus valores.';

alter table public.atajos_horas enable row level security;
drop policy if exists "atajos_horas_full_access" on public.atajos_horas;
create policy "atajos_horas_full_access" on public.atajos_horas for all using (true) with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Tabla `alertas_leidas`
--    Las alertas se generan en el frontend desde los datos (no se almacenan).
--    Esta tabla guarda cuáles ya fueron marcadas como leídas, para el badge
--    de "no leídas" y para no mostrar la misma alerta una y otra vez.
--
--    `clave` identifica la alerta de forma estable: por ejemplo
--    "cliente_frio:juan_perez:2026-05-17" o "stock_bajo:naranja:2026-05-17".
--    El que la genera arma la clave y este registro la marca como leída.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.alertas_leidas (
  clave      text primary key,
  tipo       text not null,
  leida_at   timestamptz not null default now()
);

comment on table public.alertas_leidas is
  'Registro de alertas que el usuario ya marcó como leídas. Las alertas se generan en frontend desde otros datos; aquí solo guardamos el estado.';
comment on column public.alertas_leidas.clave is
  'Identificador estable de la alerta. Ejemplos: "cliente_frio:juan_perez:2026-05-17", "stock_bajo:naranja". Incluir fecha si la alerta puede repetirse en el tiempo.';
comment on column public.alertas_leidas.tipo is
  'Categoría: cliente_frio, stock_bajo, dia_historico, sin_pautar, otro.';

create index if not exists idx_alertas_leidas_tipo
  on public.alertas_leidas (tipo);

alter table public.alertas_leidas enable row level security;
drop policy if exists "alertas_leidas_full_access" on public.alertas_leidas;
create policy "alertas_leidas_full_access"
  on public.alertas_leidas
  for all
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Claves de configuración para tarifa y umbrales de alertas
--    Misma estrategia idempotente que la migración P2: insert solo si no existe.
--    NOTA: `costo_hora_operador` y `horas_trabajadas_total` ya se insertaron
--    en la migración P2 (esos no se duplican gracias al `where not exists`).
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.config (clave, valor)
select v.clave, v.valor
from (values
  ('alerta_cliente_dias',  14),     -- días sin compra para marcar cliente VIP como frío
  ('alerta_stock_dias',    5),      -- días de stock para alerta de "stock bajo"
  ('alerta_sin_pauta_dias',5)       -- días sin pautar para alerta de marketing
) as v(clave, valor)
where not exists (
  select 1 from public.config c where c.clave = v.clave
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Seeds: personas y roles iniciales
--    Solo se insertan si no existen ya (idempotente).
--    Tarifas iniciales sugeridas (CLP/hora) — el usuario las edita desde la app.
-- ─────────────────────────────────────────────────────────────────────────────

-- Personas placeholder (el usuario edita los nombres)
insert into public.personas (nombre, orden)
select v.nombre, v.orden
from (values
  ('Persona 1', 1),
  ('Persona 2', 2)
) as v(nombre, orden)
where not exists (select 1 from public.personas);

-- Los 5 roles iniciales con tarifas sugeridas — todo editable
insert into public.roles (nombre, tarifa_hora, color, orden)
select v.nombre, v.tarifa_hora, v.color, v.orden
from (values
  ('Operación',         8000, '#00C8C8', 1),  -- producción de tragos, atención de pedidos
  ('Delivery',          6000, '#22C55E', 2),  -- manejar y entregar
  ('Compras / Logística', 5000, '#f59e0b', 3), -- ir a comprar, ordenar stock
  ('Marketing / Diseño', 8000, '#C4005A', 4), -- IG, fotos, creativos
  ('Aseo / Mantención',  4000, '#7B2FBE', 5)  -- limpieza, organización
) as v(nombre, tarifa_hora, color, orden)
where not exists (select 1 from public.roles);

-- ─────────────────────────────────────────────────────────────────────────────
-- Rollback manual (si fuera necesario):
-- drop table if exists public.horas_trabajadas;
-- drop table if exists public.atajos_horas;
-- drop table if exists public.roles;
-- drop table if exists public.personas;
-- drop table if exists public.alertas_leidas;
-- delete from public.config where clave in (
--   'alerta_cliente_dias','alerta_stock_dias','alerta_sin_pauta_dias'
-- );
